Create extension spec
catalystneuro/ndx-fiber-photometry pull request #1
Opened 2024-04-12 10:17 UTC by alessandratrapani

See #2 
The current implementation follow this schema:
![ndx-fiber-photometry](https://github.com/catalystneuro/ndx-fiber-photometry/assets/55453048/db48dab4-75f3-4b8d-81e7-906f4dc258ad)

TODOs:
- [x] add commanded voltages
- [x] add tests

2024-04-12 13:16 UTC, alessandratrapani commented
@luiztauffer @pauladkisson @weiglszonja 
I forgot to ask you about the commanded voltage series: where would you add them?

2024-04-15 13:03 UTC, luiztauffer commented
I'm not sure I like `xxxx_wavelength_in_nm` or `xxxx_bandwidth_in_nm`. I can see some advantage in being explicit about the units, but that's not pynwb standard, usually this is something we define in the doc of the attributes

2024-04-15 13:30 UTC, luiztauffer commented on src/spec/create_extension_spec.py
> +                name="fiber_photometry_table",
```suggestion
                name="fiber_photometry_table_region",
```

2024-04-15 16:48 UTC, pauladkisson commented
> I'm not sure I like `xxxx_xxxxx_in_nm`. I can see some advantage in being explicit about the units, but that's not pynwb standard, usually this is something we define in the doc of the attributes

I second this.

2024-04-15 16:59 UTC, pauladkisson commented
> we're also missing the `Fluorophore` class here, right?

I think we had decided to just include the fluorophore as a text field (here `indicator`) to avoid the complexity of excitation/emission spectra (which can be easily looked up by name anyway).  We do still need optional `injection_location` and `injection_coordinates` fields tho.

PS sorry for editing your comment -- it was an accident.

2024-04-15 17:25 UTC, pauladkisson commented
> I forgot to ask you about the commanded voltage series: where would you add them?

How about we have a `commanded_voltages` field in the `FiberPhotometryResponseSeries` that points to a `CommandedVoltageSeries` object with data [ntimes x nfibers] (same shape as `FiberPhotometryResponseSeries` object)?

2024-04-16 06:47 UTC, alessandratrapani commented
> > I'm not sure I like `xxxx_xxxxx_in_nm`. I can see some advantage in being explicit about the units, but that's not pynwb standard, usually this is something we define in the doc of the attributes.
> 
> I second this.

We discuss this with @rly and @CodyCBakerPhD. If we store it as an attribute, we add the unit of measures as in `xxxx_xxxxx_in_xx`. If we store it as a dataset, we can add a `unit` attribute to it. But they prefer to have it in the name of the field to reinforce the use of the correct U.M.

2024-04-16 06:49 UTC, alessandratrapani commented
> > we're also missing the `Fluorophore` class here, right?
> 
> I think we had decided to just include the fluorophore as a text field (here `indicator`) to avoid the complexity of excitation/emission spectra (which can be easily looked up by name anyway). We do still need optional `injection_location` and `injection_coordinates` fields tho.

How do you feel about making it an extension of `LabMetadata`, and adding optional `injection_location` and `injection_coordinates` fields?

2024-04-16 07:13 UTC, luiztauffer commented
> We discuss this with @rly and @CodyCBakerPhD. If we store it as an attribute, we add the unit of measures as in xxxx_xxxxx_in_xx. If we store it as a dataset, we can add a unit attribute to it. But they prefer to have it in the name of the field to reinforce the use of the correct U.M.

I find this strage still... can you point out any pynwb class that follows this pattern, as an example? And then, if we do this, shouldn't we do this for every attribute that has U.M.? Coordinates, for example...


> > > we're also missing the `Fluorophore` class here, right?
> > 
> > 
> > I think we had decided to just include the fluorophore as a text field (here `indicator`) to avoid the complexity of excitation/emission spectra (which can be easily looked up by name anyway). We do still need optional `injection_location` and `injection_coordinates` fields tho.
> 
> How do you feel about making it an extension of `LabMetadata`, and adding optional `injection_location` and `injection_coordinates` fields?

I'm also confused about this, I might have missed the point in our meeting. It feels like `indicator` (previously `fluorophore`) has multiple attributes: `name`, `injection_location`, `injection_coordinates`, and potentially others such as `description`... then wouldn't make sense to have it as a separate class as well? Or, what would be the disadvantage of that?
I'm not sure if that fits well within a `LabMetadata`... what if there are multiple indicators?

2024-04-16 14:01 UTC, rly commented
Hi all, regarding units, I recommend we discuss that here: https://github.com/NeurodataWithoutBorders/nwb-schema/issues/569

In brief, I think there are many good reasons to adopt a new convention `name_in_units`. For backwards compatibility reasons, we cannot easily change the names in the core standard (it is doable but it will take some time to do right). I think that maintaining consistency with a suboptimal convention should not prevent us from improving the standard for new data types. If we agree with the new convention, then I think we should recommend this new convention as a best practice for extensions and in new data types that we add to the core, and consider changing the names for existing fields in the core standard later.

2024-04-16 14:05 UTC, luiztauffer commented
> Hi all, regarding units, I recommend we discuss that here: [NeurodataWithoutBorders/nwb-schema#569](https://github.com/NeurodataWithoutBorders/nwb-schema/issues/569)
> 
> In brief, I think there are many good reasons to adopt a new convention `name_in_units`. For backwards compatibility reasons, we cannot easily change the names in the core standard (it is doable but it will take some time to do right). I think that maintaining consistency with a suboptimal convention should not prevent us from improving the standard for new data types. If we agree with the new convention, then I think we should recommend this new convention as a best practice for extensions and in new data types that we add to the core, and consider changing the names for existing fields in the core standard later.

ok cool, if this is the convention that should be followed by any new extensions, I support it!

2024-04-16 21:38 UTC, pauladkisson commented
> Hi all, regarding units, I recommend we discuss that here: [NeurodataWithoutBorders/nwb-schema#569](https://github.com/NeurodataWithoutBorders/nwb-schema/issues/569)

I was unaware of this new best practice, but it sounds good to me.  Thanks for putting together a clear write-up!

2024-04-16 21:48 UTC, pauladkisson commented
> I'm not sure if that fits well within a LabMetadata... what if there are multiple indicators?

I also think LabMetadata is a bit of a weird fit.  Indicators are functionally similar to `Device` (even though calling it a device is a bit of a misnomer) -- they often have manufacturers and lot # identifiers.

2024-04-25 14:41 UTC, weiglszonja commented on notebooks/metadata_example.yaml
> +      indicator: indicator
shouldn't this be a list of entries?
e.g. 

```yaml
Ophys:
  FiberPhotometry:
    FiberPhotometryTable:
      - location: SNc
        coordinates: [-3.25, 1.55, -3.8]
        indicator: GCaMP6f
        optical_fiber: chGreen,
        excitation_source: ExcitationSource470,
        photodetector: PhotodetectorPMT,
        dichroic_mirror: dichroic0,
        emission_filter: optical_filter_1,
    FiberPhotometryResponseSeries:
      - name: FiberPhotometryResponseSeriesGreen  # or FiberPhotometryResponseSeriesGCaMP6?
        description: Green fluorescence collected during 470 nm illumination re-binned to 100 Hz
        fiber_photometry_table_region: [0]
```

To be able to identify which excitation source device etc. to create for each `FiberPhotometryResponseSeries`

2024-04-25 15:03 UTC, weiglszonja commented
Thank you @alessandratrapani for working on this! I'll have to figure out how to modify the existing interfaces for this metadata structure (see my comment above), but overall this looks really great.

2024-04-25 17:26 UTC, weiglszonja commented on src/pynwb/tests/integration/test_fiber_photometry.py
> +    return nwbfile
I would use `pynwb.testing.mock.file.mock_NWBFile()` instead

2024-04-25 18:46 UTC, pauladkisson requested changes
Thanks for putting this together @alessandratrapani!

I caught some typos and suggested that we drop MultiCommandedVoltage, but otherwise this is looking great!

2024-04-25 18:46 UTC, pauladkisson commented on src/spec/create_extension_spec.py
> +                doc="Fluorophore injection location in stereotactic coordinates (AP, ML, DV) mm relative to Bregma.",
```suggestion
                doc="Indicator injection location in stereotactic coordinates (AP, ML, DV) mm relative to Bregma.",
```

2024-04-25 18:46 UTC, pauladkisson commented on src/spec/create_extension_spec.py
> +        doc="Extends Device to hold metadata on the Optica Fiber.",
```suggestion
        doc="Extends Device to hold metadata on the Optical Fiber.",
```

2024-04-25 18:46 UTC, pauladkisson commented on src/spec/create_extension_spec.py
> +        doc="Extends Device to hold metadata on the Excitation Source.",
```suggestion
        doc="Extends Device to hold metadata on the Photodetector.",
```

2024-04-25 18:46 UTC, pauladkisson commented on src/spec/create_extension_spec.py
> +                doc="Model of excitation source device.",
```suggestion
                doc="Model of photodetector device.",
```

2024-04-25 18:46 UTC, pauladkisson commented on src/spec/create_extension_spec.py
> +                name="commandedvoltage_series",
```suggestion
                name="commanded_voltage_series",
```
Or `commanded_voltage` like you have in the diagram.

2024-04-25 18:46 UTC, pauladkisson commented on src/spec/create_extension_spec.py
> +    multi_commanded_voltage = NWBGroupSpec(
I don't think we need this anymore since commanded voltages are going directly in the FiberPhotometryTable.

2024-04-25 18:46 UTC, pauladkisson commented on notebooks/metadata_example.yaml
> +      coordinates: [0.0, 0.0, 0.0] # Fiber placement taxonomical coordinates in (AP, ML, Z) in mm relative to Bregma
```suggestion
      coordinates: [0.0, 0.0, 0.0] # Fiber placement stereotactic coordinates in (AP, ML, DV) in mm relative to Bregma
```

2024-04-26 09:02 UTC, alessandratrapani commented on notebooks/metadata_example.yaml
> +    #     coordinates: [0.0, 0.0, 0.0] # Fluorophore injection site in taxonomical coordinates in (AP, ML, Z) in mm relative to Bregma
yes

2024-04-26 17:44 UTC, pauladkisson approved these changes
LGTM

2024-04-30 13:10 UTC, merged